# Generated by Django 4.2.10 on 2024-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_comment_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="recomend",
            field=models.BooleanField(default=True),
        ),
    ]
